name: restaurantmanagement
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sidebarx: ^0.16.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_helpers: ^0.6.1
  flutter_bloc: ^8.1.3
  firebase_storage: ^11.6.0
  google_sign_in: ^6.2.1
  go_router: ^13.0.1
  cloud_firestore: ^4.14.0
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  fpdart: ^1.1.0
  kt_dart: ^1.1.0
  firebase_ui_firestore: ^1.5.15
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
